### ISSUE TITLE
Invitation to Open-Source

### ISSUE THREAD

**Issue by mahimairaja** [muratali016/ChatGPT-Prompt-Assistant-and-Website-Chatbot#1]
Appreciations to the creative works. Your app is really fantastic. I would like to invite you to contribute to the open-source - [Project](https://github.com/mahimai-raja/open-source-python-projects-2023 )

**Comment by muratali016** [comment]
Hi, thanks for the kind offer. I'm going to create more complicated projects maybe these projects would be better for that. I will think about that again once I created my new projects.
thanks again

**Comment by mahimairaja** [comment]
Thank you @muratali016
